In [1]:
import numpy as np

In [4]:
x = np.array([[1, 2, 3, 4]]).T
x

array([[1],
       [2],
       [3],
       [4]])

In [5]:
y = np.array([[10, 20, 30, 40]]).T
y

array([[10],
       [20],
       [30],
       [40]])

In [6]:
x + y

array([[11],
       [22],
       [33],
       [44]])

In [7]:
x * 3

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [9]:
# 브로드캐스팅
x + 3 

array([[4],
       [5],
       [6],
       [7]])